apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-tilbakekreving
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  startup:
    path: /isalive
    initialDelay: 10
    failureThreshold: 6
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /isalive
    failureThreshold: 6
    periodSeconds: 10
  readiness:
    path: /isready
    failureThreshold: 3
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  env:
    - name: DRY_RUN
      value: "true"
  kafka:
    pool: "{{ kafka.pool }}"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-behandling
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
